p=int(input("Enter the prime number(p)"))
print("The value of P is",p)
q=int(input("Enter the primitive root(q)"))
print("The value of q is",q)
#senders private key
a = int(input("Enter the private key for A: "))
print("The private key a for A:", a)
x = (q**a%p)
b=int(input("Enter the private key for B"))
print("The private key for B:",b) 
y=(q**b%p) 
ka=(y**a%p)
print("The secret key for A is",ka)
kb=(x**b%p)
print("The secret key for B is",kb)